services:
  db:
    image: postgres:14
    env_file: .env
    expose:
      - '5432'
    volumes:
      - groupProject-Betwise:/var/lib/postgresql/data
      - ./ProjectSourceCode/src/init_data:/docker-entrypoint-initdb.d
  web:
    image: node:lts
    user: 'node'
    working_dir: /repository/src
    env_file: .env
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - ./:/repository
    command: "npm run testandrun"

volumes:
  groupProject-Betwise: